// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '[KEY]',
    appId: '1:352076094993:web:a12aa37ea5e2db089ddbb0',
    messagingSenderId: '352076094993',
    projectId: 'automatenfinder-376614',
    authDomain: 'automatenfinder-376614.firebaseapp.com',
    storageBucket: 'automatenfinder-376614.appspot.com',
    measurementId: 'G-8XFCC8V33M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '[KEY]',
    appId: '1:352076094993:android:eb206530b0d1d1e89ddbb0',
    messagingSenderId: '352076094993',
    projectId: 'automatenfinder-376614',
    storageBucket: 'automatenfinder-376614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '[KEY]',
    appId: '1:352076094993:ios:82133d12647193c19ddbb0',
    messagingSenderId: '352076094993',
    projectId: 'automatenfinder-376614',
    storageBucket: 'automatenfinder-376614.appspot.com',
    iosClientId: '352076094993-mo9stfgvg73tnuji4c4um8tg29h7g8jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.automatenfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '[KEY]',
    appId: '1:352076094993:ios:82133d12647193c19ddbb0',
    messagingSenderId: '352076094993',
    projectId: 'automatenfinder-376614',
    storageBucket: 'automatenfinder-376614.appspot.com',
    iosClientId: '352076094993-mo9stfgvg73tnuji4c4um8tg29h7g8jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.automatenfinder',
  );
}
